In [49]:
import numpy as np
import pandas as pd
df = pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [50]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [51]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [53]:
print(x.shape)
print(y.shape)

(768, 8)
(768,)

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [55]:
pip install keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [56]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout
import kerastuner as kt

In [57]:
def build_model(hp):

  model = Sequential()
  counter = 0

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                      activation=hp.Choice('activation'+str(i),values=['relu','tanh']),
                      input_dim=8))
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                      activation=hp.Choice('activation'+str(i),values=['relu','tanh'])))
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
      counter+=1

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer = hp.Choice('optimizer',values=['rmsprop','adam','sgd','nadam','adadelta']),
                loss ='binary_crossentropy',
                metrics = ['accuracy'])
  return model

In [58]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name ='All hyperparameters in one code h ye')

Reloading Tuner from mydir/All hyperparameters in one code h ye/tuner0.json

In [59]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [60]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 80,
 'activation0': 'tanh',
 'dropout0': 0.6,
 'optimizer': 'sgd',
 'units1': 64,
 'activation1': 'tanh',
 'dropout1': 0.5,
 'units2': 88,
 'activation2': 'Sigmoid',
 'dropout2': 0.4}

In [61]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [62]:
model.fit(X_train,y_train,epochs=200,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6678 - loss: 0.6105 - val_accuracy: 0.7403 - val_loss: 0.5572
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7280 - loss: 0.5796 - val_accuracy: 0.7468 - val_loss: 0.5410
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6873 - loss: 0.6082 - val_accuracy: 0.7468 - val_loss: 0.5333
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.5626 - val_accuracy: 0.7403 - val_loss: 0.5236
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6906 - loss: 0.5859 - val_accuracy: 0.7403 - val_loss: 0.5150
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.5589 - val_accuracy: 0.7468 - val_loss: 0.5088
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5270 - val_accuracy: 0.7403 - val_loss: 0.5067
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5343 - val_accuracy: 0.7468 - val_loss: 0.5018
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7345 - loss: 0.5376 - val_accuracy: 0.7403 - val_loss: 0.5000
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7231 - loss: 0.5558 - val_accuracy: 0.7468 - val_loss: 0.4985
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.5284 - val_accuracy: 0.7468 - val_loss: 0.4944
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5311 - val_accuracy: 0.7532 - val_loss: 0.4933
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7199 - loss: 0.5403 - val_accuracy: 0.7532 - val_loss: 0.4910
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5110 - val_accuracy: 0.7532 - val_loss: 0.4914
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7231 - loss: 0.5418 - val_accuracy: 0.7532 - val_loss: 0.4913
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7508 - loss: 0.5153 - val_accuracy: 0.7532 - val_loss: 0.4903
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7378 - loss: 0.5305 - val_accuracy: 0.7532 - val_loss: 0.4901
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5171 - val_accuracy: 0.7532 - val_loss: 0.4898
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7378 - loss: 0.5328 - val_accuracy: 0.7532 - val_loss: 0.4892
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.5069 - val_accuracy: 0.7532 - val_loss: 0.4886
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.5145 - val_accuracy: 0.7532 - val_loss: 0.4877
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5190 - val_accuracy: 0.7532 - val_loss: 0.4870
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7524 - loss: 0.5069 - val_accuracy: 0.7532 - val_loss: 0.4851
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7362 - loss: 0.5078 - val_accuracy: 0.7532 - val_loss: 0.4845
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4756 - val_accuracy: 0.7468 - val_loss: 0.4843
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7378 - loss: 0.5263 - val_accuracy: 0.7532 - val_loss: 0.4843
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7638 - loss: 0.4891 - val_accuracy: 0.7532 - val_loss: 0.4868
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7557 - loss: 0.5197 - val_accuracy: 0.7468 - val_loss: 0.4869
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.5024 - val_accuracy: 0.7468 - val_loss: 0.4873
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7345 - loss: 0.5100 - val_accuracy: 0.7403 - val_loss: 0.4869
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.5067 - val_accuracy: 0.7403 - val_loss: 0.4869
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5021 - val_accuracy: 0.7468 - val_loss: 0.4879
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4994 - val_accuracy: 0.7532 - val_loss: 0.4872
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.5041 - val_accuracy: 0.7532 - val_loss: 0.4873
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5185 - val_accuracy: 0.7468 - val_loss: 0.4873
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4969 - val_accuracy: 0.7468 - val_loss: 0.4884
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4897 - val_accuracy: 0.7468 - val_loss: 0.4891
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4857 - val_accuracy: 0.7338 - val_loss: 0.4891
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7459 - loss: 0.5171 - val_accuracy: 0.7403 - val_loss: 0.4884
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5274 - val_accuracy: 0.7403 - val_loss: 0.4881
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5092 - val_accuracy: 0.7403 - val_loss: 0.4887
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4816 - val_accuracy: 0.7403 - val_loss: 0.4885
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4902 - val_accuracy: 0.7403 - val_loss: 0.4881
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4808 - val_accuracy: 0.7403 - val_loss: 0.4891
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4823 - val_accuracy: 0.7338 - val_loss: 0.4904
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7508 - loss: 0.5044 - val_accuracy: 0.7468 - val_loss: 0.4884
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4922 - val_accuracy: 0.7403 - val_loss: 0.4898
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5052 - val_accuracy: 0.7468 - val_loss: 0.4897
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7459 - loss: 0.5189 - val_accuracy: 0.7468 - val_loss: 0.4885
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5006 - val_accuracy: 0.7468 - val_loss: 0.4897
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4987 - val_accuracy: 0.7468 - val_loss: 0.4895
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.5146 - val_accuracy: 0.7468 - val_loss: 0.4883
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4912 - val_accuracy: 0.7597 - val_loss: 0.4884
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4924 - val_accuracy: 0.7597 - val_loss: 0.4887
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7427 - loss: 0.5182 - val_accuracy: 0.7468 - val_loss: 0.4890
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5069 - val_accuracy: 0.7468 - val_loss: 0.4900
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4996 - val_accuracy: 0.7532 - val_loss: 0.4888
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5038 - val_accuracy: 0.7532 - val_loss: 0.4887
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4760 - val_accuracy: 0.7468 - val_loss: 0.4888
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5209 - val_accuracy: 0.7468 - val_loss: 0.4890
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.4787 - val_accuracy: 0.7468 - val_loss: 0.4890
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7508 - loss: 0.5047 - val_accuracy: 0.7468 - val_loss: 0.4891
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.4841 - val_accuracy: 0.7468 - val_loss: 0.4899
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4829 - val_accuracy: 0.7403 - val_loss: 0.4908
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.4874 - val_accuracy: 0.7403 - val_loss: 0.4916
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4945 - val_accuracy: 0.7403 - val_loss: 0.4922
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4790 - val_accuracy: 0.7403 - val_loss: 0.4928
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5013 - val_accuracy: 0.7403 - val_loss: 0.4925
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4972 - val_accuracy: 0.7403 - val_loss: 0.4919
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5064 - val_accuracy: 0.7403 - val_loss: 0.4920
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4875 - val_accuracy: 0.7468 - val_loss: 0.4913
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5012 - val_accuracy: 0.7468 - val_loss: 0.4903
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4972 - val_accuracy: 0.7403 - val_loss: 0.4905
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.4964 - val_accuracy: 0.7532 - val_loss: 0.4896
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4825 - val_accuracy: 0.7468 - val_loss: 0.4908
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4961 - val_accuracy: 0.7532 - val_loss: 0.4906
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4915 - val_accuracy: 0.7468 - val_loss: 0.4906
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4878 - val_accuracy: 0.7403 - val_loss: 0.4914
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4976 - val_accuracy: 0.7403 - val_loss: 0.4928
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4873 - val_accuracy: 0.7403 - val_loss: 0.4938
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4807 - val_accuracy: 0.7403 - val_loss: 0.4934
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4706 - val_accuracy: 0.7403 - val_loss: 0.4943
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4882 - val_accuracy: 0.7403 - val_loss: 0.4942
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4847 - val_accuracy: 0.7403 - val_loss: 0.4939
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4717 - val_accuracy: 0.7403 - val_loss: 0.4950
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4838 - val_accuracy: 0.7403 - val_loss: 0.4943
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.4832 - val_accuracy: 0.7338 - val_loss: 0.4944
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4638 - val_accuracy: 0.7338 - val_loss: 0.4950
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4849 - val_accuracy: 0.7338 - val_loss: 0.4949
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.4890 - val_accuracy: 0.7403 - val_loss: 0.4946
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5024 - val_accuracy: 0.7403 - val_loss: 0.4942
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4915 - val_accuracy: 0.7468 - val_loss: 0.4941
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4832 - val_accuracy: 0.7403 - val_loss: 0.4953
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4932 - val_accuracy: 0.7338 - val_loss: 0.4956
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4723 - val_accuracy: 0.7338 - val_loss: 0.4965
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4892 - val_accuracy: 0.7338 - val_loss: 0.4965
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4872 - val_accuracy: 0.7338 - val_loss: 0.4971
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4867 - val_accuracy: 0.7403 - val_loss: 0.4969
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4760 - val_accuracy: 0.7403 - val_loss: 0.4962
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4831 - val_accuracy: 0.7338 - val_loss: 0.4964
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4805 - val_accuracy: 0.7403 - val_loss: 0.4956
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4795 - val_accuracy: 0.7403 - val_loss: 0.4956
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4966 - val_accuracy: 0.7403 - val_loss: 0.4958
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4874 - val_accuracy: 0.7403 - val_loss: 0.4967
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4798 - val_accuracy: 0.7403 - val_loss: 0.4970
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4762 - val_accuracy: 0.7403 - val_loss: 0.4974
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4720 - val_accuracy: 0.7403 - val_loss: 0.4967
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7638 - loss: 0.4826 - val_accuracy: 0.7403 - val_loss: 0.4970
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7573 - loss: 0.4858 - val_accuracy: 0.7403 - val_loss: 0.4973
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7622 - loss: 0.4693 - val_accuracy: 0.7403 - val_loss: 0.4975
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.4770 - val_accuracy: 0.7403 - val_loss: 0.4981
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7704 - loss: 0.4942 - val_accuracy: 0.7403 - val_loss: 0.4982
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7655 - loss: 0.4852 - val_accuracy: 0.7403 - val_loss: 0.4985
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4631 - val_accuracy: 0.7403 - val_loss: 0.4982
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.4842 - val_accuracy: 0.7403 - val_loss: 0.4977
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7687 - loss: 0.4838 - val_accuracy: 0.7403 - val_loss: 0.4985
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4671 - val_accuracy: 0.7338 - val_loss: 0.4997
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4822 - val_accuracy: 0.7338 - val_loss: 0.4987
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4807 - val_accuracy: 0.7338 - val_loss: 0.5003
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4804 - val_accuracy: 0.7403 - val_loss: 0.5007
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4725 - val_accuracy: 0.7403 - val_loss: 0.5014
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4820 - val_accuracy: 0.7403 - val_loss: 0.4994
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4919 - val_accuracy: 0.7403 - val_loss: 0.4990
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4862 - val_accuracy: 0.7403 - val_loss: 0.4992
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4826 - val_accuracy: 0.7403 - val_loss: 0.5002
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4809 - val_accuracy: 0.7403 - val_loss: 0.5003
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4770 - val_accuracy: 0.7403 - val_loss: 0.4995
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4797 - val_accuracy: 0.7468 - val_loss: 0.4983
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4817 - val_accuracy: 0.7532 - val_loss: 0.4978
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4853 - val_accuracy: 0.7468 - val_loss: 0.4989
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4809 - val_accuracy: 0.7468 - val_loss: 0.4990
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4806 - val_accuracy: 0.7403 - val_loss: 0.4992
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4879 - val_accuracy: 0.7532 - val_loss: 0.4980
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4843 - val_accuracy: 0.7532 - val_loss: 0.4966
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4801 - val_accuracy: 0.7532 - val_loss: 0.4969
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4799 - val_accuracy: 0.7532 - val_loss: 0.4974
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5056 - val_accuracy: 0.7532 - val_loss: 0.4966
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4630 - val_accuracy: 0.7532 - val_loss: 0.4974
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4867 - val_accuracy: 0.7403 - val_loss: 0.4978
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.4946 - val_accuracy: 0.7468 - val_loss: 0.4975
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4744 - val_accuracy: 0.7403 - val_loss: 0.4974
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4768 - val_accuracy: 0.7532 - val_loss: 0.4962
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4821 - val_accuracy: 0.7468 - val_loss: 0.4966
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4669 - val_accuracy: 0.7468 - val_loss: 0.4977
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4801 - val_accuracy: 0.7468 - val_loss: 0.4980
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4720 - val_accuracy: 0.7403 - val_loss: 0.4985
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4728 - val_accuracy: 0.7403 - val_loss: 0.4995
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4784 - val_accuracy: 0.7403 - val_loss: 0.5002
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4779 - val_accuracy: 0.7403 - val_loss: 0.5008
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4627 - val_accuracy: 0.7403 - val_loss: 0.5007
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4875 - val_accuracy: 0.7403 - val_loss: 0.5004
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4678 - val_accuracy: 0.7403 - val_loss: 0.5008
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.4884 - val_accuracy: 0.7403 - val_loss: 0.5009
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4817 - val_accuracy: 0.7403 - val_loss: 0.5001
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4782 - val_accuracy: 0.7403 - val_loss: 0.4998
Epoch 162/200